//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tervisepaevik.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tervisepaevik.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aktiivne.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lisa uus treening.
        /// </summary>
        internal static string AddWorkout {
            get {
                return ResourceManager.GetString("AddWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kogus (ml).
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kogus.
        /// </summary>
        internal static string Amount1 {
            get {
                return ResourceManager.GetString("Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hommikusöök.
        /// </summary>
        internal static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hommikusöögi kalorikogus moodustab tavaliselt 25–30% päevasest kalorikogusest, mis on keskmiselt 400–600 kcal..
        /// </summary>
        internal static string BreakfastInfo {
            get {
                return ResourceManager.GetString("BreakfastInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hingamine.
        /// </summary>
        internal static string Breathing {
            get {
                return ResourceManager.GetString("Breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hingamise harjutus.
        /// </summary>
        internal static string Breathing_exercise {
            get {
                return ResourceManager.GetString("Breathing exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hingamise harjutus.
        /// </summary>
        internal static string BreathingExercise {
            get {
                return ResourceManager.GetString("BreathingExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hingake sisse, kui pilt muutub suuremaks, hingake välja, kui pilt muutub väiksemaks.
        /// </summary>
        internal static string BreathingInstruction {
            get {
                return ResourceManager.GetString("BreathingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Harjutus algas....
        /// </summary>
        internal static string BreathingStarted {
            get {
                return ResourceManager.GetString("BreathingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kallaaeg.
        /// </summary>
        internal static string Call_time {
            get {
                return ResourceManager.GetString("Call time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kalorid (kcal).
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kulutud kalorid.
        /// </summary>
        internal static string Calories_burned {
            get {
                return ResourceManager.GetString("Calories burned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kaamera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linki ei saa avada.
        /// </summary>
        internal static string CannotOpenLink {
            get {
                return ResourceManager.GetString("CannotOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Süsivesikud .
        /// </summary>
        internal static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Süsivesikud (g).
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vali.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vali foto.
        /// </summary>
        internal static string ChoosePhoto {
            get {
                return ResourceManager.GetString("ChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sulge.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kas oled kindel?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sisesta korrektne vee kogus.
        /// </summary>
        internal static string Correct_ {
            get {
                return ResourceManager.GetString("Correct ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kuupäev.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kustuta.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kirjeldus.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Üksikasjad.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Õhtusöök.
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Õhtusöögi kalorikogus moodustab tavaliselt 20–25% päevasest kalorikogusest, mis on keskmiselt 400–700 kcal..
        /// </summary>
        internal static string DinnerInfo {
            get {
                return ResourceManager.GetString("DinnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sisesta roa nimi.
        /// </summary>
        internal static string EnterFoodName {
            get {
                return ResourceManager.GetString("EnterFoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sisesta treeningu nimi.
        /// </summary>
        internal static string EnterWorkoutName {
            get {
                return ResourceManager.GetString("EnterWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viga.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rasvad (g).
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rasvad.
        /// </summary>
        internal static string Fats_ {
            get {
                return ResourceManager.GetString("Fats ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enesetunne.
        /// </summary>
        internal static string Feeling {
            get {
                return ResourceManager.GetString("Feeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filtrid.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Söök.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roa nimi.
        /// </summary>
        internal static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Üldandmed.
        /// </summary>
        internal static string General_Information {
            get {
                return ResourceManager.GetString("General Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Üldandmed.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eesmärk on saavutatud!.
        /// </summary>
        internal static string GoalReached {
            get {
                return ResourceManager.GetString("GoalReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tervitus.
        /// </summary>
        internal static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tervisepäevik.
        /// </summary>
        internal static string Health_Diary {
            get {
                return ResourceManager.GetString("Health Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tervise Päevik.
        /// </summary>
        internal static string HealthDiary {
            get {
                return ResourceManager.GetString("HealthDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ajalugu.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enesetunne.
        /// </summary>
        internal static string How_I_feel {
            get {
                return ResourceManager.GetString("How I feel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enesetunne.
        /// </summary>
        internal static string HowIfeel {
            get {
                return ResourceManager.GetString("HowIfeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toit.
        /// </summary>
        internal static string InfoFood {
            get {
                return ResourceManager.GetString("InfoFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tuju.
        /// </summary>
        internal static string InfoMood {
            get {
                return ResourceManager.GetString("InfoMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vesi.
        /// </summary>
        internal static string InfoWater {
            get {
                return ResourceManager.GetString("InfoWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treening.
        /// </summary>
        internal static string InfoWorkout {
            get {
                return ResourceManager.GetString("InfoWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vahepala.
        /// </summary>
        internal static string Interlude {
            get {
                return ResourceManager.GetString("Interlude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sisesta korrektne vee kogus.
        /// </summary>
        internal static string InvalidWater {
            get {
                return ResourceManager.GetString("InvalidWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kcal.
        /// </summary>
        internal static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lõunasöök.
        /// </summary>
        internal static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lõunasöögi kalorikogus moodustab tavaliselt 30–40% päevasest kalorikogusest, mis on keskmiselt 600–900 kcal..
        /// </summary>
        internal static string LunchInfo {
            get {
                return ResourceManager.GetString("LunchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Söök.
        /// </summary>
        internal static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menüü.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ml.
        /// </summary>
        internal static string Ml {
            get {
                return ResourceManager.GetString("Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tuju.
        /// </summary>
        internal static string Mood {
            get {
                return ResourceManager.GetString("Mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minu treeningud.
        /// </summary>
        internal static string MyWorkouts {
            get {
                return ResourceManager.GetString("MyWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Söök.
        /// </summary>
        internal static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ei.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Foto.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valgud (g).
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kogus.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valmis.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lähtesta.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salvesta.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salvestatud.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Otsi rooga....
        /// </summary>
        internal static string SearchFood {
            get {
                return ResourceManager.GetString("SearchFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vali.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vali tuju ja energia enne salvestamist.
        /// </summary>
        internal static string SelectMoodEnergy {
            get {
                return ResourceManager.GetString("SelectMoodEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valige vee kogus.
        /// </summary>
        internal static string SelectWaterAmount {
            get {
                return ResourceManager.GetString("SelectWaterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaata graafikut.
        /// </summary>
        internal static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vahepala.
        /// </summary>
        internal static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vahepalad moodustavad tavaliselt 10–15% päevasest kalorikogusest, mis on keskmiselt 200–400 kcal..
        /// </summary>
        internal static string SnackInfo {
            get {
                return ResourceManager.GetString("SnackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alusta.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avaleht.
        /// </summary>
        internal static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kas olete valmis alustama oma teekonda tervisliku keha poole?.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aeg.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kellaaeg.
        /// </summary>
        internal static string Time1 {
            get {
                return ResourceManager.GetString("Time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treeningud.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tüüp.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treeningu tüüp.
        /// </summary>
        internal static string Type_of_workout {
            get {
                return ResourceManager.GetString("Type of workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video link.
        /// </summary>
        internal static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaata graafikut.
        /// </summary>
        internal static string View_the_graph {
            get {
                return ResourceManager.GetString("View the graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Veejälgimine.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Veetaseme näidik.
        /// </summary>
        internal static string Water_level_indicator {
            get {
                return ResourceManager.GetString("Water level indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vee jälgimine.
        /// </summary>
        internal static string Water_Monitoring {
            get {
                return ResourceManager.GetString("Water Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Joodud vee kogus (ml).
        /// </summary>
        internal static string WaterAmountPlaceholder {
            get {
                return ResourceManager.GetString("WaterAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ärge unustage vett juua!.
        /// </summary>
        internal static string WaterDescription {
            get {
                return ResourceManager.GetString("WaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vee tarbimise graafik.
        /// </summary>
        internal static string WaterGraph {
            get {
                return ResourceManager.GetString("WaterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 klaas = 200 ml. Soovitatav: 2–3 liitrit päevas..
        /// </summary>
        internal static string WaterInfo {
            get {
                return ResourceManager.GetString("WaterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Veetaseme näidik.
        /// </summary>
        internal static string WaterLevel {
            get {
                return ResourceManager.GetString("WaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Veejalgimine.
        /// </summary>
        internal static string WaterMonitoring {
            get {
                return ResourceManager.GetString("WaterMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vesi.
        /// </summary>
        internal static string WaterTitle {
            get {
                return ResourceManager.GetString("WaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vee jälgimine.
        /// </summary>
        internal static string WaterTracking {
            get {
                return ResourceManager.GetString("WaterTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tere tulemast!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tervitatav.
        /// </summary>
        internal static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lisa uus treening.
        /// </summary>
        internal static string Workout {
            get {
                return ResourceManager.GetString("Workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treening.
        /// </summary>
        internal static string Workout1 {
            get {
                return ResourceManager.GetString("Workout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pange treening juba täna kava!.
        /// </summary>
        internal static string WorkoutDescription {
            get {
                return ResourceManager.GetString("WorkoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treeningu nimi.
        /// </summary>
        internal static string WorkoutName {
            get {
                return ResourceManager.GetString("WorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treeningud.
        /// </summary>
        internal static string Workouts {
            get {
                return ResourceManager.GetString("Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Treening.
        /// </summary>
        internal static string WorkoutTitle {
            get {
                return ResourceManager.GetString("WorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jah.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
