//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tervisepaevik.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tervisepaevik.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiivne.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa uus treening.
        /// </summary>
        internal static string AddWorkout {
            get {
                return ResourceManager.GetString("AddWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogus (ml).
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogus.
        /// </summary>
        internal static string Amount1 {
            get {
                return ResourceManager.GetString("Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hommikusöök.
        /// </summary>
        internal static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hingamine.
        /// </summary>
        internal static string Breathing {
            get {
                return ResourceManager.GetString("Breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hingamise harjutus.
        /// </summary>
        internal static string Breathing_exercise {
            get {
                return ResourceManager.GetString("Breathing exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hingamise harjutus.
        /// </summary>
        internal static string BreathingExercise {
            get {
                return ResourceManager.GetString("BreathingExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hingake sisse, kui pilt muutub suuremaks,\nhingake välja, kui pilt muutub väiksemaks.
        /// </summary>
        internal static string BreathingInstruction {
            get {
                return ResourceManager.GetString("BreathingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harjutus algas....
        /// </summary>
        internal static string BreathingStarted {
            get {
                return ResourceManager.GetString("BreathingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kallaaeg.
        /// </summary>
        internal static string Call_time {
            get {
                return ResourceManager.GetString("Call time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalorid (kcal).
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulutud kalorid.
        /// </summary>
        internal static string Calories_burned {
            get {
                return ResourceManager.GetString("Calories burned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaamera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linki ei saa avada.
        /// </summary>
        internal static string CannotOpenLink {
            get {
                return ResourceManager.GetString("CannotOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süsivesikud .
        /// </summary>
        internal static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süsivesikud (g).
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali foto.
        /// </summary>
        internal static string ChoosePhoto {
            get {
                return ResourceManager.GetString("ChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulge.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kas oled kindel?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta korrektne vee kogus.
        /// </summary>
        internal static string Correct_ {
            get {
                return ResourceManager.GetString("Correct ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuupäev.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjeldus.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üksikasjad.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Õhtusöök.
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta roa nimi.
        /// </summary>
        internal static string EnterFoodName {
            get {
                return ResourceManager.GetString("EnterFoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta treeningu nimi.
        /// </summary>
        internal static string EnterWorkoutName {
            get {
                return ResourceManager.GetString("EnterWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viga.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasvad (g).
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasvad.
        /// </summary>
        internal static string Fats_ {
            get {
                return ResourceManager.GetString("Fats ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enesetunne.
        /// </summary>
        internal static string Feeling {
            get {
                return ResourceManager.GetString("Feeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrid.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söök.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roa nimi.
        /// </summary>
        internal static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üldandmed.
        /// </summary>
        internal static string General_Information {
            get {
                return ResourceManager.GetString("General Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üldandmed.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tervitus.
        /// </summary>
        internal static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tervisepäevik.
        /// </summary>
        internal static string Health_Diary {
            get {
                return ResourceManager.GetString("Health Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tervise Päevik.
        /// </summary>
        internal static string HealthDiary {
            get {
                return ResourceManager.GetString("HealthDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajalugu.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enesetunne.
        /// </summary>
        internal static string How_I_feel {
            get {
                return ResourceManager.GetString("How I feel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enesetunne.
        /// </summary>
        internal static string HowIfeel {
            get {
                return ResourceManager.GetString("HowIfeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahepala.
        /// </summary>
        internal static string Interlude {
            get {
                return ResourceManager.GetString("Interlude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta korrektne vee kogus.
        /// </summary>
        internal static string InvalidWater {
            get {
                return ResourceManager.GetString("InvalidWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kcal.
        /// </summary>
        internal static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lõunasöök.
        /// </summary>
        internal static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söök.
        /// </summary>
        internal static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüü.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string Ml {
            get {
                return ResourceManager.GetString("Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuju.
        /// </summary>
        internal static string Mood {
            get {
                return ResourceManager.GetString("Mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My workouts.
        /// </summary>
        internal static string MyWorkouts {
            get {
                return ResourceManager.GetString("MyWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söök.
        /// </summary>
        internal static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgud (g).
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogus.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valmis.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvestatud.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otsi rooga....
        /// </summary>
        internal static string SearchFood {
            get {
                return ResourceManager.GetString("SearchFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali tuju ja energia enne salvestamist.
        /// </summary>
        internal static string SelectMoodEnergy {
            get {
                return ResourceManager.GetString("SelectMoodEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaata graafikut.
        /// </summary>
        internal static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahepala.
        /// </summary>
        internal static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alusta.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaleht.
        /// </summary>
        internal static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kas olete valmis alustama oma teekonda tervisliku keha poole?.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aeg.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kellaaeg.
        /// </summary>
        internal static string Time1 {
            get {
                return ResourceManager.GetString("Time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeningud.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüüp.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeningu tüüp.
        /// </summary>
        internal static string Type_of_workout {
            get {
                return ResourceManager.GetString("Type of workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video link.
        /// </summary>
        internal static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaata graafikut.
        /// </summary>
        internal static string View_the_graph {
            get {
                return ResourceManager.GetString("View the graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veejälgimine.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veetaseme näidik.
        /// </summary>
        internal static string Water_level_indicator {
            get {
                return ResourceManager.GetString("Water level indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vee jälgimine.
        /// </summary>
        internal static string Water_Monitoring {
            get {
                return ResourceManager.GetString("Water Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joodud vee kogus (ml).
        /// </summary>
        internal static string WaterAmountPlaceholder {
            get {
                return ResourceManager.GetString("WaterAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vee tarbimise graafik.
        /// </summary>
        internal static string WaterGraph {
            get {
                return ResourceManager.GetString("WaterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veetaseme näidik.
        /// </summary>
        internal static string WaterLevel {
            get {
                return ResourceManager.GetString("WaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veejalgimine.
        /// </summary>
        internal static string WaterMonitoring {
            get {
                return ResourceManager.GetString("WaterMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vee jälgimine.
        /// </summary>
        internal static string WaterTracking {
            get {
                return ResourceManager.GetString("WaterTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tere tulemast!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tervitatav.
        /// </summary>
        internal static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa uus treening.
        /// </summary>
        internal static string Workout {
            get {
                return ResourceManager.GetString("Workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treening.
        /// </summary>
        internal static string Workout1 {
            get {
                return ResourceManager.GetString("Workout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeningu nimi.
        /// </summary>
        internal static string WorkoutName {
            get {
                return ResourceManager.GetString("WorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeningud.
        /// </summary>
        internal static string Workouts {
            get {
                return ResourceManager.GetString("Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jah.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
